M48
; DRILL file {KiCad (6.0.7)} date Mon Jun 26 07:17:28 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-26T07:17:28-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X8.2313Y-2.6862
X8.4222Y-2.6862
T2
X8.2195Y-2.5669
X8.4341Y-2.5669
T0
M30
