M48
; DRILL file {KiCad (6.0.7)} date Fri Apr 21 16:09:54 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-21T16:09:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.999Y-1.7335
X5.19Y-1.7335
T2
X4.9872Y-1.6142
X5.2018Y-1.6142
T0
M30
